"use client";

import { Archive, Bold, BookOpen, CheckSquare, ChevronDown, Code, Copy, Filter, Folder, Italic, Link, List, ListOrdered, Lock, MoreHorizontal, MousePointer2, Plus, Presentation, Search, Share2, SortAsc, Sparkles, Star, Type, Underline } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useNotes } from "./hooks/useNotes";
import type { NoteEntity, NotebookListItem, NotesFilter, NotesSort, Permission } from "./models/notes.models";
import styles from "./Notes.module.css";

const sorts: [NotesSort, string][] = [["manual", "Manual order"], ["alphabetical", "Alphabetical"], ["recentlyEdited", "Recently edited"], ["recentlyCreated", "Recently created"], ["oldestFirst", "Oldest first"], ["newestFirst", "Newest first"]];
const filters: [NotesFilter, string][] = [["all", "All notes"], ["favorites", "Favorites"], ["recent", "Recently edited"], ["shared", "Shared"], ["archived", "Archived"]];

export function Notes() {
  const notes = useNotes();
  const [menu, setMenu] = useState<string | null>(null);
  const [shareOpen, setShareOpen] = useState(false);
  const [presenting, setPresenting] = useState(false);
  const [canvasSwitcherOpen, setCanvasSwitcherOpen] = useState(false);
  const [editingNotebookId, setEditingNotebookId] = useState<string | null>(null);
  const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
  const editorRef = useRef<HTMLDivElement>(null);
  const selected = notes.data?.selectedNote;

  const cmd = useCallback((command: string, value?: string) => { document.execCommand(command, false, value); editorRef.current?.focus(); }, []);
  const addLink = useCallback(() => { const url = prompt("Paste a link"); if (url) cmd("createLink", url); }, [cmd]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setPresenting(false); if ((e.ctrlKey || e.metaKey) && selected) { if (e.key.toLowerCase() === "b") { e.preventDefault(); document.execCommand("bold"); } if (e.key.toLowerCase() === "i") { e.preventDefault(); document.execCommand("italic"); } if (e.key.toLowerCase() === "k") { e.preventDefault(); addLink(); } if (e.shiftKey && e.key === "7") { e.preventDefault(); document.execCommand("insertOrderedList"); } if (e.shiftKey && e.key === "8") { e.preventDefault(); document.execCommand("insertUnorderedList"); } } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [addLink, selected]);
  useEffect(() => { if (editorRef.current && selected && editorRef.current.innerHTML !== selected.body) editorRef.current.innerHTML = selected.body; }, [selected]);
  const coming = () => alert("Coming Soon");
  if (!notes.state || !notes.data) return <main className={styles.loading}>Loading notes…</main>;

  if (presenting) return <main className={styles.present} tabIndex={0}><button onClick={() => setPresenting(false)}>Exit presentation</button><article dangerouslySetInnerHTML={{ __html: selected?.body ?? "<h1>No note selected</h1>" }} /></main>;

  const counts = { favorites: notes.state.notebooks.filter((n) => n.favorite && !n.archived).length + notes.state.notes.filter((n) => n.favorite && !n.archived).length, shared: notes.state.notebooks.filter((n) => n.shared && !n.archived).length + notes.state.notes.filter((n) => n.shared && !n.archived).length, archive: notes.state.notebooks.filter((n) => n.archived).length + notes.state.notes.filter((n) => n.archived).length };

  return <main className={styles.notes} onClick={() => { setMenu(null); setCanvasSwitcherOpen(false); }}>
    <aside className={styles.panel}>
      <header className={styles.header}><h1>Notes <Sparkles size={22}/></h1><p>Your thinking, connected.</p></header>
      <div className={styles.toolbar}><IconButton label="New notebook" onClick={notes.actions.createNotebook}><Plus/></IconButton><IconButton label="New note" onClick={() => notes.actions.createNote()}><Folder/></IconButton><label className={styles.selectControl}><SortAsc size={16}/><select aria-label="Sort notebooks" value={notes.state.notebookSort} onChange={(e) => notes.actions.setNotebookSort(e.target.value as NotesSort)}>{sorts.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className={styles.selectControl}><Filter size={16}/><select aria-label="Filter notes" value={notes.state.filter} onChange={(e) => notes.actions.setFilter(e.target.value as NotesFilter)}>{filters.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label></div>
      <label className={styles.search}><Search size={18}/><input value={notes.notebookQuery} onChange={(e) => notes.setNotebookQuery(e.target.value)} placeholder="Search notebooks..."/><span>⌘K</span></label>
      <Section title="Notebooks"><div className={styles.bookList}>{notes.data.notebooks.length ? notes.data.notebooks.map((book) => <Notebook key={book.id} book={book} active={selected?.id} selectedBookId={notes.state!.selectedNotebookId} actions={notes.actions} setMenu={setMenu} menu={menu} editingNotebookId={editingNotebookId} setEditingNotebookId={setEditingNotebookId} editingNoteId={editingNoteId} setEditingNoteId={setEditingNoteId}/>) : <Empty label="No matching notes" action="Clear filter" onClick={() => notes.actions.setFilter("all")}/>}</div></Section>
      <nav className={styles.nav}><button onClick={() => notes.actions.setFilter("favorites")}><Star size={16} fill="#fbbf24"/>Favorites<span>{counts.favorites}</span></button><button onClick={() => notes.actions.setFilter("shared")}><Share2 size={16}/>Shared with me<span>{counts.shared}</span></button><button onClick={() => notes.actions.setFilter("archived")}><Archive size={16}/>Archive<span>{counts.archive}</span></button></nav>
    </aside>
    <section className={styles.workspace}>
      <header className={styles.topbar}><div className={styles.crumb}><strong>{notes.data.selectedNotebook?.title ?? "Notebook"}</strong><span>›</span><CanvasSwitcher open={canvasSwitcherOpen} onToggle={(event) => { event.stopPropagation(); setCanvasSwitcherOpen((open) => !open); }} onClose={() => setCanvasSwitcherOpen(false)} notes={notes.data.selectedNotebook ? notes.state.notes.filter((note) => note.notebookId === notes.data!.selectedNotebook!.id && !note.archived) : []} selectedId={selected?.id ?? null} onSelect={(id) => { notes.actions.selectNote(id); setCanvasSwitcherOpen(false); }}/></div><div className={styles.actions}><label className={styles.topSelect}><SortAsc size={16}/><select aria-label="Sort canvases" value={notes.state.noteSort} onChange={(e) => notes.actions.setNoteSort(e.target.value as NotesSort)}>{sorts.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><button onClick={() => setShareOpen(true)}><Share2 size={16}/>Share</button><button onClick={(e) => { e.stopPropagation(); setMenu("more"); }}><MoreHorizontal size={18}/></button><button className={styles.presentBtn} onClick={() => setPresenting(true)}><Presentation size={16}/>Present</button>{menu === "more" && <Menu><button onClick={() => selected && notes.actions.duplicateNote(selected.id)}>Duplicate note</button><button onClick={() => selected && notes.actions.archiveNote(selected.id)}>{selected?.archived ? "Restore note" : "Archive note"}</button><button onClick={() => selected && notes.actions.deleteNote(selected.id)}>Delete note</button></Menu>}</div></header>
      <label className={styles.canvasSearch}><Search size={18}/><input value={notes.noteQuery} onChange={(e) => notes.setNoteQuery(e.target.value)} placeholder={`Search in ${notes.data.selectedNotebook?.title ?? "notebook"} canvas...`}/><span>⌘ F</span></label>
      <div className={styles.format}><select onChange={(e) => cmd("formatBlock", e.target.value)}><option value="H2">H2</option><option value="H1">H1</option><option value="P">Text</option></select><button onClick={() => cmd("bold")}><Bold/></button><button onClick={() => cmd("italic")}><Italic/></button><button onClick={() => cmd("underline")}><Underline/></button><button onClick={() => cmd("formatBlock", "PRE")}><Code/></button><button onClick={() => cmd("insertUnorderedList")}><List/></button><button onClick={() => cmd("insertOrderedList")}><ListOrdered/></button><button onClick={() => cmd("insertHTML", '<label><input type="checkbox"/> Task</label>')}><CheckSquare/></button><button onClick={addLink}><Link/></button></div>
      <article className={styles.canvas}>{selected ? <><input className={styles.titleInput} value={selected.title} onChange={(e) => notes.actions.patchNote(selected.id, { title: e.target.value })}/><div ref={editorRef} className={styles.editor} contentEditable suppressContentEditableWarning onInput={(e) => notes.actions.patchNote(selected.id, { body: e.currentTarget.innerHTML })}/></> : <Empty label={notes.data.selectedNotebook ? "No notes in this notebook" : "No notebook selected"} action="New note" onClick={() => notes.actions.createNote()}/>}</article>
      <div className={styles.bottomTools}>{[MousePointer2, Type, Copy, Link, CheckSquare, Search, MoreHorizontal].map((I, i) => <button key={i} onClick={coming}><I size={20}/></button>)}</div><div className={styles.zoom}><button onClick={coming}>−</button><span>100%</span><button onClick={coming}>+</button><Lock size={16}/></div>
    </section>
    {shareOpen && selected && <ShareModal note={selected} onClose={() => setShareOpen(false)} onSave={(patch) => notes.actions.patchNote(selected.id, patch)}/>} {notes.toast && <div className={styles.toast}>{notes.toast}<button onClick={notes.undo}>Undo</button></div>}
  </main>;
}

function CanvasSwitcher({open,onToggle,onClose,notes,selectedId,onSelect}:{open:boolean;onToggle:(event:React.MouseEvent)=>void;onClose:()=>void;notes:NoteEntity[];selectedId:string|null;onSelect:(id:string)=>void}) { const selectedIndex=Math.max(0, notes.findIndex((note)=>note.id===selectedId)); const [focusIndex,setFocusIndex]=useState(selectedIndex); return <div className={styles.canvasSwitcher}><button type="button" aria-haspopup="listbox" aria-expanded={open} className={styles.canvasSwitchButton} onClick={onToggle} onKeyDown={(e)=>{ if(e.key==="ArrowDown"){e.preventDefault();setFocusIndex((i)=>Math.min(notes.length-1,i+1));} if(e.key==="ArrowUp"){e.preventDefault();setFocusIndex((i)=>Math.max(0,i-1));} if(e.key==="Enter"&&open&&notes[focusIndex]){e.preventDefault();onSelect(notes[focusIndex].id);} if(e.key==="Escape"){e.preventDefault();onClose();}}}><strong>{notes.find((note)=>note.id===selectedId)?.title ?? "Canvas"}</strong><ChevronDown size={16}/></button>{open&&<div className={styles.canvasMenu} role="listbox" onClick={(e)=>e.stopPropagation()}>{notes.map((note,index)=><button key={note.id} type="button" role="option" aria-selected={note.id===selectedId} className={`${note.id===selectedId?styles.selectedCanvas:""} ${index===focusIndex?styles.focusedCanvas:""}`} onMouseEnter={()=>setFocusIndex(index)} onClick={()=>onSelect(note.id)}>{note.title}</button>)}</div>}</div>; }
function Section(p: {title: string; children: React.ReactNode}) { return <section className={styles.section}><h2>{p.title}</h2>{p.children}</section>; }
function Empty(p: {label: string; action: string; onClick: () => void}) { return <div className={styles.empty}><p>{p.label}</p><button onClick={p.onClick}>{p.action}</button></div>; }
function IconButton(p: {label: string; children: React.ReactNode; onClick: () => void}) { return <button title={p.label} onClick={p.onClick}>{p.children}</button>; }
function RenameInput({value,onSave,onCancel}:{value:string;onSave:(value:string)=>void;onCancel:()=>void}) { const [draft,setDraft]=useState(value); const save=()=>{ const next=draft.trim(); onSave(next || value); }; return <input className={styles.renameInput} value={draft} autoFocus onClick={(e)=>e.stopPropagation()} onDoubleClick={(e)=>e.stopPropagation()} onChange={(e)=>setDraft(e.target.value)} onBlur={save} onKeyDown={(e)=>{ if(e.key==="Enter") save(); if(e.key==="Escape") onCancel(); }}/>; }
function BookRow({book,onClick,actions,setMenu,menu,selected,editing,setEditing}: {book: NotebookListItem; onClick:()=>void; actions: ReturnType<typeof useNotes>["actions"]; setMenu:(m:string|null)=>void; menu:string|null; selected?: boolean; editing:boolean; setEditing:(id:string|null)=>void}) { return <div draggable onDragStart={(e)=>e.dataTransfer.setData("book",book.id)} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>actions.moveNotebook(e.dataTransfer.getData("book"),book.id)} onContextMenu={(e)=>{e.preventDefault();setMenu(book.id)}} className={`${styles.bookRow} ${selected ? styles.activeBook : ""}`} onClick={onClick}><span style={{background:book.color}}><BookOpen size={14}/></span><b onDoubleClick={(e)=>{e.stopPropagation();setEditing(book.id);}}>{editing ? <RenameInput value={book.title} onSave={(title)=>{actions.patchNotebook(book.id,{title});setEditing(null);}} onCancel={()=>setEditing(null)}/> : <>{book.title}{book.archived && <em className={styles.badge}>Archived</em>}</>}</b><small>{book.noteCount} canvases</small><button onClick={(e)=>{e.stopPropagation();actions.patchNotebook(book.id,{favorite:!book.favorite})}}><Star size={14} fill={book.favorite?"#fbbf24":"none"}/></button>{menu===book.id&&<Context book={book} actions={actions}/>}</div>; }
function Notebook({book,active,selectedBookId,actions,setMenu,menu,editingNotebookId,setEditingNotebookId,editingNoteId,setEditingNoteId}: {book: NotebookListItem; active?:string; selectedBookId:string|null; actions: ReturnType<typeof useNotes>["actions"]; setMenu:(m:string|null)=>void; menu:string|null; editingNotebookId:string|null; setEditingNotebookId:(id:string|null)=>void; editingNoteId:string|null; setEditingNoteId:(id:string|null)=>void}) { return <div className={styles.current}><BookRow book={book} selected={selectedBookId===book.id} onClick={()=>{actions.selectNotebook(book.id);actions.patchNotebook(book.id,{collapsed:!book.collapsed});}} actions={actions} setMenu={setMenu} menu={menu} editing={editingNotebookId===book.id} setEditing={setEditingNotebookId}/>{!book.collapsed && book.visibleNotes.map(n=><button key={n.id} draggable onDragStart={(e)=>e.dataTransfer.setData("note",n.id)} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>actions.moveNote(e.dataTransfer.getData("note"),book.id)} onContextMenu={(e)=>{e.preventDefault();setMenu(n.id)}} className={active===n.id?styles.activeNote:styles.noteRow} onClick={()=>actions.selectNote(n.id)}><span/> <b className={styles.noteTitle} onDoubleClick={(e)=>{e.stopPropagation();setEditingNoteId(n.id);}}>{editingNoteId===n.id ? <RenameInput value={n.title} onSave={(title)=>{actions.patchNote(n.id,{title});setEditingNoteId(null);}} onCancel={()=>setEditingNoteId(null)}/> : n.title}</b><Star size={13} fill={n.favorite?"#fbbf24":"none"} onClick={(e)=>{e.stopPropagation();actions.patchNote(n.id,{favorite:!n.favorite})}}/>{menu===n.id&&<Menu><button onClick={()=>actions.patchNote(n.id,{title:prompt("Rename note",n.title)||n.title})}>Rename</button><button onClick={()=>actions.duplicateNote(n.id)}>Duplicate</button><button onClick={()=>actions.patchNote(n.id,{favorite:!n.favorite})}>Favorite</button><button onClick={()=>actions.archiveNote(n.id)}>{n.archived?"Restore":"Archive"}</button><button onClick={()=>actions.deleteNote(n.id)}>Delete</button></Menu>}</button>)}<button className={styles.addCanvas} onClick={()=>actions.createNote(book.id)}>+ New canvas in this notebook</button></div>; }
function Context({book,actions}: {book: NotebookListItem; actions: ReturnType<typeof useNotes>["actions"]}) { return <Menu><button onClick={()=>actions.patchNotebook(book.id,{title:prompt("Rename notebook",book.title)||book.title})}>Rename</button><button onClick={()=>actions.duplicateNotebook(book.id)}>Duplicate</button><button onClick={()=>actions.patchNotebook(book.id,{collapsed:!book.collapsed})}>{book.collapsed?"Expand":"Collapse"}</button><button onClick={()=>actions.patchNotebook(book.id,{favorite:!book.favorite})}>Favorite</button><button onClick={()=>actions.archiveNotebook(book.id)}>{book.archived?"Restore":"Archive"}</button><button onClick={()=>actions.deleteNotebook(book.id)}>Delete</button></Menu>; }
function Menu({children}:{children:React.ReactNode}) { return <div className={styles.menu} onClick={(e)=>e.stopPropagation()}>{children}</div>; }
function ShareModal({note,onClose,onSave}:{note:NoteEntity;onClose:()=>void;onSave:(p:Partial<NoteEntity>)=>void}) { const [email,setEmail]=useState(""); return <div className={styles.scrim}><div className={styles.modal}><h2>Share “{note.title}”</h2><label><input type="checkbox" checked={note.publicLink} onChange={(e)=>onSave({publicLink:e.target.checked})}/> Public link</label><div className={styles.shareLine}><input value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="teammate@example.com"/><select value={note.permission} onChange={(e)=>onSave({permission:e.target.value as Permission})}><option>viewer</option><option>editor</option><option>owner</option></select></div><button onClick={()=>{if(email)onSave({shared:true,sharedWith:[...note.sharedWith,email]});setEmail("");}}>Share with user</button><button onClick={()=>navigator.clipboard?.writeText(`${location.origin}/notes/${note.id}`)}>Copy Link</button><button onClick={onClose}>Done</button></div></div>; }
