import type {Metadata, Viewport} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#F7F4ED",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable}`}
          suppressHydrationWarning
      >
      <body className="min-h-screen bg-background text-text font-sans antialiased">
      {children}
      </body>
      </html>
  );
}