import { readFileSync, writeFileSync } from 'node:fs';
const folder='plans/before-after';
const manifest=JSON.parse(readFileSync(`${folder}/manifest.json`,'utf8'));
const sections=manifest.screens.map(s=>`<section id="screen-${s.number}"><header><h2>${s.number}. ${s.name}</h2><span class="status">${s.status}</span></header>
<p class="meta">Reference viewport assumption: ${s.width} × ${s.height} CSS px · checkpoint ${s.checkpoint} · capture ${s.capturedAt.slice(0,10)} · code ${s.currentCommit}</p>
<div class="pair"><figure><figcaption>BEFORE <small>Actual Phase 3 UI · ${manifest.baseline}</small></figcaption><a href="before-${s.number}-full.png"><img src="before-${s.number}.png" alt="${s.name} before Phase 4" loading="lazy" width="${s.width}" height="${s.height}"></a></figure>
<figure><figcaption>AFTER / CURRENT <small>${s.status.startsWith('Pending')?'Not restyled yet':'Phase 4 implementation'}</small></figcaption><a href="after-${s.number}-full.png"><img src="after-${s.number}.png" alt="Current ${s.name} screen" loading="lazy" width="${s.width}" height="${s.height}"></a></figure></div>
<details><summary>Design reference and current mobile capture</summary><div class="reference"><figure><figcaption>DESIGN REFERENCE <small>Supplied ${s.number}.png — target, not “before”</small></figcaption><a href="../new%20cohort%20creation%20flow/${s.number}.png"><img src="../new%20cohort%20creation%20flow/${s.number}.png" alt="Supplied ${s.name} reference" loading="lazy"></a></figure><figure class="mobile"><figcaption>CURRENT MOBILE <small>390 × 844 viewport, full page</small></figcaption><a href="mobile-${s.number}.png"><img src="mobile-${s.number}.png" alt="Current ${s.name} mobile layout" loading="lazy"></a></figure></div></details></section>`).join('\n');
writeFileSync(`${folder}/index.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cohort creation — before & after</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f2eb;color:#13213b;font:15px/1.5 system-ui,sans-serif}main{max-width:1800px;margin:auto;padding:32px}h1{font-size:clamp(26px,3vw,42px);margin:0 0 12px}p{max-width:1000px}nav{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0}nav a{color:inherit;background:white;border:1px solid #ddd7cb;border-radius:20px;padding:7px 14px;text-decoration:none}section{scroll-margin-top:20px;margin:36px 0 60px}section header{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}h2{margin:0;font-size:25px}.status{background:#e8e9ff;border:1px solid #d8dbff;border-radius:18px;padding:5px 12px;font-size:12px}.meta{font-size:12px;color:#576578}.pair,.reference{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;background:white;border:1px solid #ded9cd;border-radius:14px;overflow:hidden;min-width:0}figcaption{font-weight:750;letter-spacing:.04em;font-size:12px;padding:15px 18px;border-bottom:1px solid #eee8dd}figcaption small{display:block;font-weight:400;letter-spacing:0;color:#59677b;margin-top:4px}img{display:block;width:100%;height:auto}a:focus-visible,summary:focus-visible{outline:3px solid #313aff;outline-offset:3px}summary{cursor:pointer;padding:15px 0;color:#3139a5}.reference{align-items:start}.mobile{max-width:390px;justify-self:center}.note{padding:15px 20px;border-left:3px solid #313aff;background:white} @media(max-width:850px){main{padding:20px}.pair,.reference{grid-template-columns:1fr}.status{font-size:11px}} @media print{details{display:none}section{break-inside:avoid}nav{display:none}}
</style></head><body><main><h1>Cohort creation: before & after</h1><p>Actual application components captured with identical, explicit visual fixtures. Click any image for its full-page capture. Expand a screen to see the supplied design reference and current mobile view.</p><p class="note">“Before” is the committed Phase 3 UI (${manifest.baseline}). “After” is the current code. Pending screens are not claimed complete. These are isolated rendering fixtures with mocked commands/data reads, not live authenticated AI/database journeys. Next image/link wrappers and local production fonts are used. Content, available artwork and some controls differ from the reference; final visual fidelity review remains pending.</p><nav aria-label="Screens">${manifest.screens.map(s=>`<a href="#screen-${s.number}">${s.number} · ${s.name}</a>`).join('')}</nav>${sections}<footer>Generated from manifest.json. Update after each visual checkpoint with the documented capture commands.</footer></main></body></html>\n`);
