import type { Cohort as DbCohort, Season, Lesson } from '@/generated/prisma';
import type { Cohort as UiCohort } from '@/src/client/screens/cohort/models';

export function mapDbCohortToUiCohort(dbCohort: any): UiCohort {
  return {
    id: dbCohort.id,
    title: dbCohort.title,
    subtitle: dbCohort.subtitle || '',
    description: dbCohort.description || '',
    coverImage: dbCohort.coverImage || '',
    difficulty: dbCohort.difficulty,
    categories: [],
    creator: {
      id: dbCohort.creator.id,
      name: dbCohort.creator.name || 'Creator',
      avatarUrl: dbCohort.creator.image || '',
      role: dbCohort.creator.role,
      bio: dbCohort.creator.bio || '',
      ctaLabel: 'View Profile',
    },
    stats: { rating: 5, explorerCount: 0, completionRate: 0 },
    progress: {
      journeyProgress: 0,
      completedQuests: 0,
      totalQuests: dbCohort.seasons.reduce((acc: number, s: any) => acc + s.lessons.length, 0),
      dailyGoal: '',
      joinedDate: '',
    },
    overview: {
      description: dbCohort.description || '',
      pillars: [],
      learningObjectives: [],
      journeySummary: [],
      expeditionStats: [],
      expeditionProgress: [],
      activeExplorers: [],
      activeExplorerOverflow: '',
    },
    questline: {
      title: `${dbCohort.title} Questline`,
      description: '',
      filters: [],
      skipSeasonLabel: '',
      seasons: dbCohort.seasons.map((s: any) => ({
        id: s.id,
        title: s.title,
        badge: '',
        status: 'Locked',
        progress: 0,
        estimatedDuration: '',
        questCount: s.lessons.length,
        summaryLabel: '',
        lessons: s.lessons.map((l: any) => ({
          id: l.id,
          title: l.title,
          type: 'Video',
          duration: `${l.duration || 0}m`,
          status: 'Ready',
          totalChunks: 1,
          completedChunks: 0,
          thumbnail: '',
          videoId: l.videoUrl,
          videoUrl: l.videoUrl,
          chunks: [],
        })),
      })),
      feedTitle: '',
      feedDescription: '',
      feedSeasonLabel: '',
      feedViewAllLabel: '',
      assignmentFeed: [],
      lockedFutureNotice: { icon: 'book', title: '', description: '' },
    },
    events: {
      title: '',
      description: '',
      filters: [],
      upcomingEvents: [],
      weeklySchedule: [],
      calendarSync: [],
      suggestEvent: { title: '', description: '', buttonLabel: '', illustration: '' },
    },
    archives: {
      title: '',
      description: '',
      categories: [],
      sortControls: [],
      items: [],
      contributors: [],
      trending: [],
      shareKnowledge: { title: '', description: '', buttonLabel: '', illustration: '' },
    },
    hallOfFame: {
      title: '',
      subtitle: '',
      filters: [],
      timeRanges: [],
      categories: [],
      legends: [],
      userHighlights: [],
      recentAchievements: [],
    },
  };
}
